# Generated by Django 5.0.1 on 2026-01-21 13:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeachImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='beach_images/%Y/%m/%d/')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Beach Image',
                'verbose_name_plural': 'Beach Images',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='beachImage__timesta_7a5b38_idx'), models.Index(fields=['latitude', 'longitude'], name='beachImage__latitud_f8f817_idx')],
            },
        ),
    ]
