# Generated by Django 5.0.1 on 2025-04-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcam',
            name='num_consecutive_failures',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webcam',
            name='public_url',
            field=models.CharField(blank=True, help_text='URL to redirect viewers to original source.', max_length=2048, null=True),
        ),
    ]
