# Generated by Django 5.0.1 on 2025-04-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0002_webcam_num_consecutive_failures_webcam_public_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageProvider',
        ),
        migrations.DeleteModel(
            name='StreamProvider',
        ),
        migrations.DeleteModel(
            name='YoutubeProvider',
        ),
        migrations.RemoveField(
            model_name='webcam',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='webcam',
            name='object_id',
        ),
        migrations.AddField(
            model_name='webcam',
            name='provider_image_url',
            field=models.CharField(blank=True, help_text="Can use `%Y`, `%m`, `%d`, etc. as in python's strftime(...)", max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='webcam',
            name='provider_stream_clickable_element_xpath',
            field=models.CharField(blank=True, help_text='XPath to the clickable element that generates the stream.', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='webcam',
            name='provider_stream_url',
            field=models.CharField(blank=True, help_text='Use .m3u8 or .html that generates a .m3u8 after clicking on a html element.', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='webcam',
            name='provider_youtube_url',
            field=models.CharField(blank=True, help_text='Only for https://www.youtube.com/watch?v=(...) links.', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='webcam',
            name='video_seconds',
            field=models.IntegerField(blank=True, default=10, help_text='Seconds to record for the video'),
        ),
    ]
