# Generated by Django 5.0.1 on 2025-04-10 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0003_delete_imageprovider_delete_streamprovider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webcam',
            name='available',
        ),
        migrations.RemoveField(
            model_name='webcam',
            name='probe_freq_mins',
        ),
    ]
