# Generated by Django 5.0.1 on 2025-04-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0004_remove_webcam_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcam',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
