# Generated by Django 5.0.1 on 2025-04-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0005_alter_webcam_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webcam',
            old_name='provider_stream_clickable_element_xpath',
            new_name='provider_streamfromclick_clickable_element_xpath',
        ),
        migrations.RenameField(
            model_name='webcam',
            old_name='provider_stream_url',
            new_name='provider_streamfromclick_url',
        ),
    ]
