# Generated by Django 5.0.1 on 2025-04-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0006_rename_provider_stream_clickable_element_xpath_webcam_provider_streamfromclick_clickable_element_xpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcam',
            name='provider_streamfromregex_regex',
            field=models.CharField(blank=True, help_text='Regex match.', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='webcam',
            name='provider_streamfromregex_strformat',
            field=models.CharField(blank=True, help_text="String to be formatted with regex's match[1].", max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='webcam',
            name='provider_streamfromregex_url',
            field=models.CharField(blank=True, help_text='Use .html that contains a dynamically-generated .m3u8 that can be located with a regex match.', max_length=2048, null=True),
        ),
    ]
