# Generated by Django 5.0.1 on 2025-04-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0007_webcam_provider_streamfromregex_regex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcam',
            name='provider_stream_m3u8_url',
            field=models.CharField(blank=True, help_text='.m3u8 static url', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='webcam',
            name='provider_streamfromclick_url',
            field=models.CharField(blank=True, help_text='.html url that generates a .m3u8 after clicking on a html element.', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='webcam',
            name='provider_streamfromregex_url',
            field=models.CharField(blank=True, help_text='.html url that contains a dynamically-generated .m3u8 that can be located with a regex match.', max_length=2048, null=True),
        ),
    ]
