# Generated by Django 5.0.1 on 2025-04-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0008_webcam_provider_stream_m3u8_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcam',
            name='mask_beach',
            field=models.ImageField(blank=True, help_text='Mask of the beach area (sand, areas with people, etc). For non-movable webcams only.', null=True, upload_to='masks/beach/'),
        ),
        migrations.AddField(
            model_name='webcam',
            name='mask_boats',
            field=models.ImageField(blank=True, help_text='Mask of the boat area (further from beach, deep waters). For non-movable webcams only.', null=True, upload_to='masks/ocean'),
        ),
        migrations.AddField(
            model_name='webcam',
            name='mask_swimming',
            field=models.ImageField(blank=True, help_text='Mask of the swimming area (near the beach, shallow waters). For non-movable webcams only.', null=True, upload_to='masks/swimming'),
        ),
    ]
