# Generated by Django 5.0.1 on 2025-04-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webcam", "0009_webcam_mask_beach_webcam_mask_boats_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webcam",
            name="mask_full",
            field=models.ImageField(
                blank=True,
                help_text="Mask of the full webcam (any area can be included). For non-movable webcams only",
                null=True,
                upload_to="masks/full/",
            ),
        ),
    ]
