# Generated by Django 5.0.1 on 2026-02-17 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0009_webcam_mask_beach_webcam_mask_boats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beach_slug', models.CharField(help_text='Provided by FundacioBit', max_length=200, unique=True)),
                ('beach_name', models.CharField(max_length=200)),
                ('source_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('longitud', models.CharField(blank=True, max_length=100, null=True)),
                ('anchura', models.CharField(blank=True, max_length=100, null=True)),
                ('limites', models.CharField(blank=True, max_length=255, null=True)),
                ('localizacion', models.CharField(blank=True, max_length=255, null=True)),
                ('coordenadas_geograficas', models.CharField(blank=True, max_length=255, null=True)),
                ('grado_de_ocupacion', models.CharField(blank=True, choices=[('HIGH', 'Alto'), ('MEDIUM', 'Medio'), ('LOW', 'Bajo')], max_length=20, null=True)),
                ('proximidad_al_nucleo_urbano', models.CharField(blank=True, choices=[('URBAN', 'Urbana'), ('SEMI_URBAN', 'Semiurbana'), ('REMOTE', 'Alejada')], max_length=20, null=True)),
                ('tipos_de_playas', models.CharField(blank=True, choices=[('NATURAL', 'Natural'), ('ARTIFICIAL', 'Artificial')], max_length=20, null=True)),
                ('composicion_de_la_playa', models.CharField(blank=True, choices=[('SAND', 'Arena'), ('PEBBLES', 'Bolos'), ('GRAVEL', 'Graba'), ('ROCKS', 'Rocas')], max_length=20, null=True)),
                ('condiciones_de_bano', models.CharField(blank=True, choices=[('CALM', 'Aguas tranquilas'), ('MODERATE', 'Oleaje moderado'), ('STRONG', 'Oleaje fuerte')], max_length=20, null=True)),
                ('vientos_dominantes', models.CharField(blank=True, choices=[('LIGHT_BREEZE', 'Brisa ligera'), ('DOMINANT', 'Dominante'), ('STRONG', 'Fuerte')], max_length=30, null=True)),
                ('pendiente_de_la_playa', models.CharField(blank=True, choices=[('GENTLE', 'Ángulo suave'), ('NORMAL', 'Ángulo normal'), ('STEEP', 'Pendiente brusco')], max_length=20, null=True)),
                ('paseo_maritimo', models.BooleanField(blank=True, null=True)),
                ('vegetacion', models.BooleanField(blank=True, null=True)),
                ('proximidad_a_zona_residencial', models.BooleanField(blank=True, null=True)),
                ('acceso_para_discapacitado', models.BooleanField(blank=True, null=True)),
                ('localizacion_de_accesos_para_vehiculos_de_emergencias', models.BooleanField(blank=True, null=True)),
                ('campos_de_dunas', models.BooleanField(blank=True, null=True)),
                ('marismas', models.BooleanField(blank=True, null=True)),
                ('vegetacion_protegida', models.BooleanField(blank=True, null=True)),
                ('espacio_natural_protegido', models.BooleanField(blank=True, null=True)),
                ('ondulaciones_de_fondo', models.BooleanField(blank=True, null=True)),
                ('barras_sumergidas', models.BooleanField(blank=True, null=True)),
                ('fosas', models.BooleanField(blank=True, null=True)),
                ('obstaculos_semisumergidos_o_sumergidos', models.BooleanField(blank=True, null=True)),
                ('espigones', models.IntegerField(blank=True, null=True)),
                ('puertos_mares', models.BooleanField(blank=True, null=True)),
                ('puertos_islas', models.BooleanField(blank=True, null=True)),
                ('puertos_baches', models.BooleanField(blank=True, null=True)),
                ('canal', models.BooleanField(blank=True, null=True)),
                ('arenosa', models.BooleanField(blank=True, null=True)),
                ('rocosa_en_la_montana', models.BooleanField(blank=True, null=True)),
                ('rocosa_en_costa_de_escalon', models.BooleanField(blank=True, null=True)),
                ('playa_mixta_de_grava_y_arena', models.BooleanField(blank=True, null=True)),
                ('accesos_a_la_playa_para_peatones', models.BooleanField(default=False)),
                ('accesos_a_la_playa_para_vehiculos', models.BooleanField(default=False)),
                ('accesos_a_la_playa_para_barcos', models.BooleanField(default=False)),
                ('tipo_de_usuario_local', models.BooleanField(default=False)),
                ('tipo_de_usuario_turista', models.BooleanField(default=False)),
                ('oleaje_dir_n', models.BooleanField(default=False)),
                ('oleaje_dir_ne', models.BooleanField(default=False)),
                ('oleaje_dir_e', models.BooleanField(default=False)),
                ('oleaje_dir_se', models.BooleanField(default=False)),
                ('oleaje_dir_s', models.BooleanField(default=False)),
                ('oleaje_dir_so', models.BooleanField(default=False)),
                ('oleaje_dir_o', models.BooleanField(default=False)),
                ('oleaje_dir_no', models.BooleanField(default=False)),
                ('tipos_de_olas_mar_de_fondo', models.BooleanField(default=False)),
                ('tipos_de_olas_mar_de_viento', models.BooleanField(default=False)),
                ('flujo_de_agua_centrales_termicas', models.BooleanField(default=False)),
                ('flujo_de_agua_corriente_de_marea', models.BooleanField(default=False)),
                ('flujo_de_agua_corriente_de_oleaje', models.BooleanField(default=False)),
                ('flujo_de_agua_corrientes_de_resaca', models.BooleanField(default=False)),
                ('flujo_de_agua_deriva_litoral', models.BooleanField(default=False)),
                ('flujo_de_agua_desembocaduras', models.BooleanField(default=False)),
                ('flujo_de_agua_otros', models.BooleanField(default=False)),
                ('flujo_de_agua_rieras', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='webcam',
            old_name='description',
            new_name='camera_description',
        ),
        migrations.RenameField(
            model_name='webcam',
            old_name='beach_latitude',
            new_name='camera_latitude',
        ),
        migrations.RenameField(
            model_name='webcam',
            old_name='beach_longitude',
            new_name='camera_longitude',
        ),
        migrations.RenameField(
            model_name='webcam',
            old_name='slug',
            new_name='camera_slug',
        ),
        migrations.RemoveField(
            model_name='webcam',
            name='beach_name',
        ),
        migrations.AddField(
            model_name='webcam',
            name='beach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webcams', to='webcam.beach'),
        ),
    ]