# Generated by Django 5.0.1 on 2026-02-17 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0010_beach_rename_description_webcam_camera_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcam',
            name='beach',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='webcams', to='webcam.beach'),
            preserve_default=False,
        ),
    ]
