# Generated by Django 5.0.1 on 2026-03-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0011_alter_webcam_beach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webcam',
            name='mask_beach',
        ),
        migrations.RemoveField(
            model_name='webcam',
            name='mask_boats',
        ),
        migrations.RemoveField(
            model_name='webcam',
            name='mask_swimming',
        ),
        migrations.AddField(
            model_name='webcam',
            name='filter_blurry_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webcam',
            name='filter_frozen_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webcam',
            name='filter_moving_camera',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webcam',
            name='mask_sand',
            field=models.ImageField(blank=True, help_text='Mask of the beach area (sand, areas with people, etc). For non-movable webcams only.', null=True, upload_to='masks/beach/'),
        ),
        migrations.AddField(
            model_name='webcam',
            name='mask_sand_and_water',
            field=models.ImageField(blank=True, help_text='Mask of the whole area of interest (beach + swimming water). For non-movable webcams only.', null=True, upload_to='masks/sand_and_water/'),
        ),
        migrations.AddField(
            model_name='webcam',
            name='mask_swimming_water',
            field=models.ImageField(blank=True, help_text='Mask of the swimming area (near the beach, shallow waters). For non-movable webcams only.', null=True, upload_to='masks/swimming'),
        ),
    ]
