# Generated by Django 5.0.1 on 2026-06-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webcam", "0012_remove_webcam_mask_beach_remove_webcam_mask_boats_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webcam",
            name="daytime_p90",
            field=models.FloatField(default=0),
        ),
    ]
