# Generated by Django 5.0.1 on 2024-01-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beachcam',
            name='url_aemet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='beachcam',
            name='url_platgesbalears',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='image',
            field=models.ImageField(null=True, upload_to='count/'),
        ),
    ]
