# Generated by Django 5.0.1 on 2024-05-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_prediction_algorithm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beachcam",
            name="url_image",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
