# Generated by Django 5.0.1 on 2024-06-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_prediction_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='beachcam',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
