# Generated by Django 5.0.1 on 2024-07-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_beachcam_url_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='beachcam',
            name='url_seemallorca',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
