# Generated by Django 5.0.1 on 2024-07-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_beachcam_url_seemallorca'),
    ]

    operations = [
        migrations.AddField(
            model_name='beachcam',
            name='prefered_image_provider',
            field=models.CharField(default='youtube', max_length=25),
        ),
    ]
