# Generated by Django 5.0.1 on 2024-07-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_beachcam_prefered_image_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='beachcam',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
