"""
Django settings for beachcamweb project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from django.utils.translation import gettext_lazy as _
import os

from config.local_settings import LOCAL_SETTINGS

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = LOCAL_SETTINGS.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = LOCAL_SETTINGS.DEBUG

ALLOWED_HOSTS = LOCAL_SETTINGS.ALLOWED_HOSTS


# Application definition

INSTALLED_APPS = [
    'adminfilters',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.webcam',
    'apps.prediction',
    'apps.core',
    'apps.beachImage',
    'apps.api',
    'django_apscheduler',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.core.context_processors.parent_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'development_db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale')
]

LANGUAGES = [
    ("en", _("English")),
    ("ca", _("Catalan")),
    ("es", _("Spanish")),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# run python manage.py collectstatic
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "static"


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

CSRF_TRUSTED_ORIGINS = ['https://ocupacioplatges.uib.es', 'https://ocupacioplatges.uib.cat', 'https://ocupacioplatges.uib.eu']

API_JWT_SECRET = LOCAL_SETTINGS.API_JWT_SECRET
API_JWT_ALGOS = LOCAL_SETTINGS.API_JWT_ALGOS

PYTORCH_ENABLE_MPS_FALLBACK = 1
os.putenv("PYTORCH_ENABLE_MPS_FALLBACK", "1")

# ── Prediction app paths (single root) ────────────────────────────────────────
PREDICTION_DIR    = BASE_DIR / 'apps' / 'prediction'
TFT_MODELS_DIR    = PREDICTION_DIR / 'tft_models'
XGB_MODELS_DIR    = PREDICTION_DIR / 'xgb_models'
TFT_EVAL_JSON     = PREDICTION_DIR / 'model_evaluation.json'
WEATHER_CACHE_DIR = PREDICTION_DIR / 'cache' / 'weather'
TFT_MODEL_SETS = {
    'lstm': BASE_DIR / 'apps/prediction/lstm_models/lstm_model_v4',
}
TFT_HINDCAST_CACHE_DIR = BASE_DIR / 'apps/prediction/cache/hindcast_cache'

# ── Pipeline ──────────────────────────────────────────────────────────────────
PIPELINE_MEDIA_2022_DIR = BASE_DIR / 'BeachCamDataset_NoVideos'
PIPELINE_CUDA_DEVICE    = '0'
#
# cron_every_day = '0 2 * * *'  # every day at 2:00 AM
# cron_every_week = '0 2 * * 1'   # every Monday at 2:00 AM
# cron_every_month = '0 2 1 * *'    # on the 1st of every month at 2:00 AM
# cron_every_thirty_minutes = '*/30 * * * *'  # every 30 minutes
#
# CRONJOBS = [
#     (
#         cron_every_month,
#         'django.core.management.call_command',
#         ['run_pipeline'],
#         f'>> {BASE_DIR}/pipeline_workspace/logs/pipeline.log 2>&1'
#     ),
#     (
#         cron_every_thirty_minutes,
#         'download_and_process.main',
#         [],
#         {},
#         f'>> {BASE_DIR}/logs/download.log 2>&1'
#     ),
# ]